set(PLATFORM_WIN32 0)
set(PLATFORM_WEB 1)
set(PLATFORM_UNKNOWN 2)

if(${COMPILER} EQUAL ${COMPILER_EMCC})
    set(PLATFORM ${PLATFORM_WEB})
    message("Platform is set to Web...")
elseif(${COMPILER} EQUAL ${COMPILER_MSVC})
    set(PLATFORM ${PLATFORM_WIN32})
    message("Platform is set to Win32...")
else()
    set(PLATFORM ${PLATFORM_UNKNOWN})
    message(FATAL_ERROR "Platform could not be determined!")
endif()
